- internal/cmd/todos/main.go
> fix: Don't open bad symlinks

- .gitignore
- .golangci.yml
- .markdownlint.yaml
- .markdownlintignore
- Makefile
- package-lock.json
- package.json
- requirements.txt
> chore: Add linters

- .github/workflows/pre-submit.lint.yml
- .github/workflows/pre-submit.units.yml
- .yamllint.yaml
> tests: Add pre-submits

- internal/cmd/todos/main.go
- internal/cmd/todos/options.go
- internal/todos/todos.go
> feat: Add --todo-types flag

- .github/workflows/pre-submit.codecov.yml
- Makefile
- codecov.yml
> chore: Add codecov pre-submit

- internal/cmd/todos/walker.go
> fix: errors walking bazel cache

- .github/workflows/pre-submit.autogen.yml
- .github/workflows/pre-submit.codecov.yml
- .github/workflows/pre-submit.lint.yml
- .github/workflows/pre-submit.units.yml
- .golangci.yml
- .markdownlint.yaml
- .slsa-goreleaser/darwin-amd64.yml
- .slsa-goreleaser/darwin-arm64.yml
- .slsa-goreleaser/linux-amd64.yml
- .slsa-goreleaser/linux-arm64.yml
- .slsa-goreleaser/windows-amd64.yml
- .slsa-goreleaser/windows-arm64.yml
- .yamllint.yaml
- Makefile
- codecov.yml
> chore: Autogen pre submit

- .github/workflows/pre-submit.lint.yml
- .gitignore
- .golangci.yml
- codecov.yml
- go.mod
- go.sum
- internal/cmd/todos/walker.go
- internal/scanner/scanner.go
- internal/scanner/scanner_test.go
- internal/testutils/utils.go
- internal/todos/todos_test.go
> feat: Add charset support

- .github/pr-title-checker-config.json
- .github/workflows/pre-submit.pr-title.yml
> chore: Add PR title checker

- .github/workflows/pre-submit.units.yml
- CHANGELOG.md
- codecov.yml
- internal/cmd/todos/errors/errors.go
- internal/cmd/todos/main.go
- internal/cmd/todos/options/options.go
- internal/cmd/todos/walker.go
- internal/cmd/todos/walker/utils_other.go
- internal/cmd/todos/walker/utils_other_test.go
- internal/cmd/todos/walker/utils_windows.go
- internal/cmd/todos/walker/utils_windows_test.go
- internal/cmd/todos/walker/walker.go
- internal/cmd/todos/walker/walker_test.go
- internal/cmd/todos/walker_test.go
- internal/scanner/scanner_test.go
- internal/testutils/deferrable.go
- internal/testutils/deferrable_test.go
- internal/testutils/utils_test.go
> feat: Add tests for main package

- internal/cmd/todos/walker/utils_windows_test.go
> fix: Windows test

- .github/workflows/pre-submit.lint.yml
- Makefile
> chore: add actionlint

- .github/workflows/scorecards.yml
- README.md
> chore: Add scorecard and badges

- CHANGELOG.md
- internal/cmd/todos/app.go
- internal/cmd/todos/app_test.go
- internal/walker/walker.go
> feat: Add `--include-vcs` flag

- CHANGELOG.md
- internal/scanner/config.go
- internal/scanner/scanner_test.go
> feat: Rust support

- CHANGELOG.md
- internal/todos/todos.go
> feat: Add lowercase TODO type defaults

- .github/workflows/pre-submit.units.yml
> test: add e2e pre-submits for issue-reopener

- internal/cmd/github-issue-reopener/app.go
- internal/cmd/github-issue-reopener/main.go
- internal/cmd/github-issue-reopener/reopener/reopener.go
- internal/cmd/github-issue-reopener/reopener/reopener_test.go
- internal/cmd/todos/app.go
- internal/cmd/todos/main.go
> feat: github-issue-reopener: add file filtering options

- .github/workflows/pre-submit.units.yml
- Makefile
- actions/issue-reopener/Makefile
- actions/issue-reopener/__tests__/verifier.test.ts
- actions/issue-reopener/jest.config.js
- actions/issue-reopener/jest.setup.js
- actions/issue-reopener/package-lock.json
- actions/issue-reopener/package.json
Adds basic TS test scaffolding and CI workflow along with a test of `ValidateFileDigest`
Updates #145
> test: issue-reopener TypeScript action unit tests

- .github/workflows/pre-submit.units.yml
> fix: Don't checkout code in e2e pre-submit

- .github/workflows/schedule.issue-reopener.yml
> feat: add issue-reopener workflow

- CODE_OF_CONDUCT.md
- SECURITY.md
> docs: Create CODE_OF_CONDUCT.md

- CHANGELOG.md
- internal/scanner/config.go
- internal/scanner/scanner_test.go
> feat: Haskell support

- Makefile
> feat: Add benchmark target to Makefile

- CHANGELOG.md
- internal/scanner/config.go
- internal/scanner/scanner_test.go
> feat: Erlang support

- internal/scanner/config.go
> chore: update TODO comments

- .github/workflows/pre-submit.units.yml
> ci: Add FOSSA pre-submit

- README.md
> docs: Add FAQ

- internal/cmd/todos/app.go
- internal/cmd/todos/app_test.go
- internal/utils/utils.go
- internal/utils/utils_test.go
> fix: help flag doesn't take an argument

- .github/pull_request_template.md
Fixes the link to CONTRIBUTING.md and spacing between checklist items.
N/A
**Checklist:**
> fix: PR template

- README.md
Updates the README so that installation instructions reference the newest version of v0.5.0.
**Checklist:**
> docs: Update installation instructions for v0.5.0

- README.md
- SUPPORTED_LANGUAGES.md
- codecov.yml
- internal/cmd/genlangdocs/main.go
Adds a new SUPPORTED_LANGUAGES.md doc with a list of supported languages and comments.
Fixes #720
**Checklist:**
> docs: Add supported languages doc

- CHANGELOG.md
- SUPPORTED_LANGUAGES.md
- internal/cmd/genlangdocs/main.go
- internal/scanner/languages.yml
- internal/scanner/scanner_test.go
Add support for TeX files. The `SUPPORTED_LANGUAGES.md` file is now sorted.
Updates #460 
**Checklist:**
> feat: Add TeX support

- CHANGELOG.md
- SUPPORTED_LANGUAGES.md
- internal/scanner/languages.yml
- internal/scanner/scanner_test.go
Add Emacs Lisp support.
Updates #460 
**Checklist:**
> feat: Emacs support

- CHANGELOG.md
- SUPPORTED_LANGUAGES.md
- internal/scanner/languages.yml
- internal/scanner/scanner_test.go
Add support for Puppet manifests.
Updates #460 
**Checklist:**
> feat: Puppet support

- .github/pull_request_template.md
Add a task to the checklist in the PR template to update documentation if applicable.
N/A
**Checklist:**
> ci: Add task to update docs to PR template

- .github/dependabot.yml
Make dependabot updates monthly so they don't generate so much spam. Security updates are not affected by `schedule.interval`.
N/A
**Checklist:**
> chore: Make dependabot updates monthly

- go.mod
- go.sum
Bump github.com/ianlewis/runeio from 1.0.0 to 1.1.1.
N/A
**Checklist:**
> chore(deps): Bump github.com/ianlewis/runeio from 1.0.0 to 1.1.1

- .github/workflows/pre-submit.units.yml
Add e2e test for vanityURLs option to issue-reopener.
Fixes #1190
**Checklist:**
> test: Add e2e test for vanityURLs option

- CHANGELOG.md
- SUPPORTED_LANGUAGES.md
- internal/scanner/languages.yml
- internal/scanner/scanner_test.go
Adds support for Kotlin.
Updates #460
**Checklist:**
> feat: Add support for Kotlin

- .github/workflows/schedule.issue-reopener.yml
Updates CI to use the `todo-issue-reopener` in the new repository: https://github.com/ianlewis/todo-issue-reopener
Updates #1367
**Checklist:**
> ci: Use todo-issue-reopener

- README.md
Adds alt text to the image in the README for accessibility purposes.
N/A
**Checklist:**
> docs: Add alt text

- CHANGELOG.md
Release v0.8.0
N/A
**Checklist:**
> chore(release): v1.8.0

- .github/workflows/go-ossf-slsa3-publish.yml
Fixes the release workflow.
N/A
**Checklist:**
> fix: release workflow

- .github/workflows/schedule.update-docs-pr.yml
Fixes workflow comment referring to version.
N/A
**Checklist:**
> ci(fix): workflow version comment

- .github/workflows/schedule.issue-reopener.yml
Update `todo-issue-reopener` to v1.2.1 to fix TUF error.
N/A
**Checklist:**
> chore(ci): Update todo-issue-reopener

- internal/walker/walker_test.go
Add a test for when a vendor directory is specified.
N/A
**Checklist:**
> test: Add vendor check test

- CHANGELOG.md
Fix link in the CHANGELOG.
N/A
**Checklist:**
> chore(release): fix changelog link

- .github/workflows/go-ossf-slsa3-publish.yml
- .github/workflows/pre-submit.units.yml
- go.mod
- go.sum
Updates the SLSA builder to v2.0.0.
N/A
**Checklist:**
> ci: Upgrade SLSA Go builder to v2.0.0

- CHANGELOG.md
Release v0.9.0-rc.2
N/A
**Checklist:**
> chore(release): v0.9.0-rc.2

- internal/vendoring/vendor.yml
Update copyright header of vendor.yml which was copied from GitHub's linguist project.
Fixes #1549
**Checklist:**
> chore: Update copyright header

- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/pre-submit.units.yml
- .github/workflows/schedule.issue-reopener.yml
- .github/workflows/schedule.stale.yml
- .gitignore
- .golangci.yml
- .markdownlint.yaml
- .prettierignore
- .yamllint.yaml
- CHANGELOG.md
- Makefile
- package-lock.json
- package.json
- requirements.txt
Merge with github.com/ianlewis/repo-template-go 1ee1a29
N/A
**Checklist:**
> chore: Merge with repo-template-go

- .gitignore
- Makefile
- internal/cmd/todos/app.go
- internal/cmd/todos/profile.go
- internal/cmd/todos/profile_debug.go
Add profiling support behind the `profile` build tag.
Updates #45
**Checklist:**
> feat: Add profiling support

- internal/cmd/todos/app.go
Update the copyright notice in the help.
N/A
**Checklist:**
> chore: Update copyright notice

- .github/workflows/pre-submit.units.yml
- CHANGELOG.md
- internal/cmd/todos/app.go
- internal/cmd/todos/app_test.go
- internal/walker/walker.go
- internal/walker/walker_test.go
Read `.gitignore` and `.todosignore` files and ignore files that match patterns in those files.
Fixes #125
**Checklist:**
> feat: Add ignore file support

- CHANGELOG.md
- README.md
- go.mod
- go.sum
Release v0.12.0
N/A
**Checklist:**
> chore(release): v0.12.0

- README.md
- cmd/todos/app.go
Update the README to reorder some of the sections, add a "Features" section, and add a section on installing as a Go tool dependency.
Fixes #1640 
Fixes #1655
**Checklist:**
> docs: Update README

- internal/scanner/languages.go
Remove old TODO
Fixes #1546 
**Checklist:**
> chore: Remove old TODO

- .golangci.yml
- cmd/todos/app.go
- internal/scanner/scanner_test.go
- internal/todos/todos_test.go
Enable `dupword` linter.
Updates #1678
**Checklist:**
> chore: Enable dupword linter

- .golangci.yml
- internal/scanner/scanner_test.go
Use `b.Loop()` to improve benchmarks.
n/a
**Checklist:**
> chore: Use b.Loop()

- .github/workflows/go-ossf-slsa3-publish.yml
- .gitignore
- .slsa-goreleaser/todos-darwin-amd64.yml
- .slsa-goreleaser/todos-darwin-arm64.yml
- .slsa-goreleaser/todos-linux-amd64.yml
- .slsa-goreleaser/todos-linux-arm64.yml
- .slsa-goreleaser/todos-windows-amd64.yml
- .slsa-goreleaser/todos-windows-arm64.yml
- Makefile
- package-lock.json
- package.json
Add npm packaging.
Updates #1656
Fixes #1696 
**Checklist:**
> chore: Add npm package

- .github/workflows/go-ossf-slsa3-publish.yml
- .github/workflows/pre-submit.units.yml
- Dockerfile
- Makefile
- aqua-checksums.json
- aqua.yaml
- renovate.json5
- zizmor.yml
Adds a Docker image build.
Updates #1656 
Fixes #1697
**Checklist:**
> feat: Add Docker image build

- CHANGELOG.md
- package-lock.json
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.0
n/a
**Checklist:**
> chore(release): v0.13.0-rc.0

- .github/workflows/go-ossf-slsa3-publish.yml
- zizmor.yml
Fix release workflow
n/a
**Checklist:**
> fix: release version validation

- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.1
n/a
**Checklist:**
> chore(release): v0.13.0-rc.1

- .github/workflows/go-ossf-slsa3-publish.yml
- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.2
n/a
**Checklist:**
> chore(release): v0.13.0-rc.2

- .github/workflows/go-ossf-slsa3-publish.yml
- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
- zizmor.yml
Release v0.13.0-rc.3
n/a
**Checklist:**
> chore(release): v0.13.0-rc.3

- .github/workflows/go-ossf-slsa3-publish.yml
- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.4
n/a
**Checklist:**
> chore(release): v0.13.0-rc.4

- CHANGELOG.md
Add notes on new packaging to the `CHANGELOG.md`
n/a
**Checklist:**
> docs: Add packaging notes to CHANGELOG

- .github/workflows/go-ossf-slsa3-publish.yml
- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
- zizmor.yml
Release v0.13.0-rc.5
n/a
**Checklist:**
> chore(release): v0.13.0-rc.5

- .github/workflows/go-ossf-slsa3-publish.yml
- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
- zizmor.yml
Release v0.13.0-rc.6
n/a
**Checklist:**
> chore(release): v0.13.0-rc.6

- CHANGELOG.md
- Dockerfile
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.7
n/a
**Checklist:**
> chore(release): v0.13.0-rc.7

- .github/workflows/pre-submit.units.yml
- .gitignore
- Makefile
- eslint.config.mjs
- index.js
- package-lock.json
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Fix npm package binary install.
Fixes #1712 
**Checklist:**
> fix: npm package binary install

- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.8
n/a
**Checklist:**
> chore(release): v0.13.0-rc.8

- .github/workflows/go-ossf-slsa3-publish.yml
- index.js
- package-lock.json
- zizmor.yml
Fix the platform specific binary name for npm packages
n/a
**Checklist:**
> fix: npm binary name

- .github/workflows/go-ossf-slsa3-publish.yml
- package-lock.json
- zizmor.yml
Fix binary permissions for npm packages.
n/a
**Checklist:**
> fix: npm package binary permission

- README.md
Add `rg` to the FAQ
Fixes #1702
**Checklist:**
> docs: Add rg to FAQ

- .golangci.yml
- cmd/todos/app_test.go
Enable the `reassign` linter.
Updates #1678
**Checklist:**
> chore: enable reassign linter

- .golangci.yml
- cmd/todos/app.go
- internal/scanner/scanner.go
- internal/scanner/scanner_test.go
- internal/testutils/gitrepo.go
- internal/testutils/tempdir_test.go
- internal/walker/walker.go
Enable the `varnamelen` linter.
Updates #1678
**Checklist:**
> chore: enable varnamelen

- CHANGELOG.md
- README.md
Release v0.13.0-rc.11
n/a
**Checklist:**
> chore(release): v0.13.0-rc.11

- CHANGELOG.md
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0-rc.12
n/a
**Checklist:**
> chore(release): v0.13.0-rc.12

- CHANGELOG.md
- package-lock.json
- package.json
- packages/todos-darwin-amd64/package.json
- packages/todos-darwin-arm64/package.json
- packages/todos-linux-amd64/package.json
- packages/todos-linux-arm64/package.json
- packages/todos-windows-amd64/package.json
- packages/todos-windows-arm64/package.json
Release v0.13.0
n/a
**Checklist:**
> chore(release): v0.13.0

- .textlintrc.yaml
- README.md
Add a use case instructions for Neovim.
Updates #1750
**Checklist:**
> docs: Add use case for Neovim

- internal/walker/walker.go
- internal/walker/walker_test.go
Add symlink loop detection so that `todos` will produce better results when symlink loops exist.
Fixes #1759 
**Checklist:**
> fix: Add symlink loop detection
