ianlewis/todos

CHANGELOG.md
internal/scanner/comment.go
internal/scanner/scanner.go
internal/todos/todos.go
internal/todos/todos_test.go

Fixes bugs in TODO matches so they don't match todos that start in the middle of a comment.

fix: Regex refactor

---

internal/scanner/config.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

feat: Add support for Lua

---

internal/scanner/config.go
internal/scanner/scanner_test.go

feat: Assembly support

---

.github/workflows/pre-submit.units.yml
actions/issue-reopener/jest.config.js

feat: Add coverage to TS tests

---

internal/scanner/config.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

fix: escaping in assembly

---

internal/scanner/config.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

feat: SQL support

---

CHANGELOG.md
internal/scanner/config.go
internal/scanner/scanner_test.go

feat: Add R support

---

internal/scanner/config.go

chore: Remove todo comments

---

internal/todos/todos.go
internal/todos/todos_test.go

feat: Match TODOs more loosely

---

internal/scanner/scanner.go
internal/scanner/scanner_test.go

feat: detect language by filename

---

.github/workflows/fossa.yml
.github/workflows/pre-submit.units.yml

ci: Only run Fossa at main

---

internal/scanner/config.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

linguist doesn't detect TypeScript files well so this PR adds specific detection for TypeScript files by their file extension.
Fixes #513 
**Checklist:**
You are strongly encouraged to create an issue for any change to allow for
discussion on the proposed change before actually making the changes and
proposing them via a Pull Request.
[Google CLA](https://cla.developers.google.com/about/google-corporate).
[Developer Certificate of Origin](https://developercertificate.org/)
signoff.
```text
This is my commit message
Signed-off-by: Random J Developer <random@developer.example.org>
```

fix: TypeScript detection

---

CHANGELOG.md
internal/todos/todos.go
internal/todos/todos_test.go

Adds support for a special case of TODO comments with no whitespace between the comment start and "TODO" and with no delimiter between "TODO" and the message.
```text
//TODO This is a todo comment.
```
Fixes #514 
**Checklist:**

feat: Add support for looser TODO special case

---

.github/pr-title-checker-config.json
.github/pull_request_template.md
CONTRIBUTING.md

Updates to CONTRIBUTING.md to add lots more instructions on how to contribute.
Fixes #527
**Checklist:**

docs: Update CONTRIBUTING.md

---

CHANGELOG.md
internal/todos/todos.go
internal/todos/todos_test.go

Add support for JavaDoc/JSDoc/TSDoc comments that have a leading asterisk.
```java
/**
* Some comment.
* TODO: Add some code here.
*/
```
Fixes #517 
**Checklist:**

feat: Add support for TODOs in JavaDoc

---

Makefile

Removes duplicate license header in `Makefile`
**Checklist:**

fix: Makefile license header duplication

---

.github/workflows/codeql.yml
.github/workflows/fossa.yml

Set top level token permissions for GitHub Actions workflows.
**Checklist:**

chore(security): Add top level token permissions

---

CHANGELOG.md
internal/scanner/scanner.go

Detect the language of each file based on it's file name if able. This makes language detection much faster since the file contents do not need to be read.
Fixes #518 
**Checklist:**

refactor: Detect language by filename

---

CHANGELOG.md
internal/scanner/languages.yml
internal/scanner/scanner_test.go

Adds support for [CoffeeScript](https://coffeescript.org/) language files.
Updates #460 
**Checklist:**

feat: Coffeescript support

---

CHANGELOG.md
internal/todos/todos.go
internal/todos/todos_test.go

Updates the TODO parser to report all TODOs in a multi-line comment.
Fixes #709 
**Checklist:**

fix: report all TODOs in a multi-line comment

---

CHANGELOG.md
README.md
internal/scanner/languages.yml
internal/scanner/scanner_test.go
internal/todos/todos.go
internal/todos/todos_test.go

Add support for the parsing TODOs from Clojure files.
Updates #460 
**Checklist:**

feat: Clojure support

---

CHANGELOG.md
README.md
internal/todos/todos.go
internal/todos/todos_test.go

Adds support for `@` prefix on TODOs ala the old JavaDoc style.
e.g.
```java
/**
* @todo: foo
*/
```
Fixes #516 
**Checklist:**

feat: Support `@` prefixes

---

internal/todos/todos.go
internal/todos/todos_test.go

Fixes panic when no matches occur in multi-line comment.
Fixes #776 
**Checklist:**

fix: panic when no matches occur in multi-line comment

---

CHANGELOG.md
internal/scanner/languages.yml
internal/scanner/scanner_test.go

Adds support for Groovy files.
Updates #460 
**Checklist:**

feat: Groovy support

---

Makefile
actions/issue-reopener/Makefile

Updates the clean makefile target so that it doesn't delete files in the `dist` directory for Github Actions. The main `clean` target also runs `make clean` for GitHub Actions as well as for the main Go code.
N/A
**Checklist:**

chore: Update clean make target

---

CHANGELOG.md
internal/scanner/languages.go
internal/scanner/languages.yml
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Add support for recognizing the multi-line comments that only begin at the start of a line.
Fixes #665 
**Checklist:**

feat: Support multi-line comments at line start

---

CHANGELOG.md
Makefile
SUPPORTED_LANGUAGES.md
internal/scanner/languages.yml
internal/scanner/scanner_test.go
package-lock.json
package.json

Add support for Visual Basic 6 (VBA) and Visual Basic .NET
Updates #460
**Checklist:**

feat: Add Visual Basic support

---

Makefile
internal/scanner/scanner_test.go

Fix benchmarks so that they run multiple times in a loop. This allows them to be timed properly.
Updates #45 
**Checklist:**

fix: benchmarks now run multiple times

---

.slsa-goreleaser/todos-darwin-amd64.yml
.slsa-goreleaser/todos-darwin-arm64.yml
.slsa-goreleaser/todos-linux-amd64.yml
.slsa-goreleaser/todos-linux-arm64.yml
.slsa-goreleaser/todos-windows-amd64.yml
.slsa-goreleaser/todos-windows-arm64.yml

Add -s -w ldflags to SLSA builder config so that release binaries have debug symbols stripped. This results in smaller binaries.
Fixes #1082
**Checklist:**

ci: Add -s -w ldflags to release

---

.github/workflows/schedule.issue-reopener.yml

Updates the hash for todo-issue-reopener to the correct value.
Updates #1367 
**Checklist:**

fix: update todo-issue-reopener hash

---

CHANGELOG.md
internal/cmd/todos/app.go

Default the `--output` flag to `github` when `GITHUB_ACTIONS` is `true` for ease of use on GitHub Actions.
Fixes #1459
**Checklist:**

fix: default output to github on GitHub Actions

---

CHANGELOG.md
internal/cmd/todos/app.go
internal/cmd/todos/app_test.go

`--exclude-dir` now ignores trailing path separators on the directory name passed to it. This is since it's natural to pass something like `mydir/` as a directory name.
Fixes #1463
**Checklist:**

fix: exclude-dir not matching with path separator

---

.github/workflows/schedule.update-docs-pr.yml

Adds a workflow to create a PR for updating docs to reference the latest version.
N/A
**Checklist:**

ci: Add docs update automation

---

CHANGELOG.md
SUPPORTED_LANGUAGES.md
internal/scanner/languages.yml
internal/scanner/scanner_test.go

Adds support for Fortran.
Updates #460 
**Checklist:**

feat: Fortran support

---

internal/walker/walker.go

Remove `.github` as a special case for vendoring.
N/A
**Checklist:**

fix: Remove .github special case

---

internal/walker/walker.go

Fix vendoring checks.
N/A
**Checklist:**

fix: Vendor check

---

CHANGELOG.md
internal/cmd/todos/app.go
internal/walker/walker.go
internal/walker/walker_test.go

Ignore generated files by default. A new option `--include-generated` overrides this behavior.
Fixes #1506
**Checklist:**

feat: Ignore generated files

---

CHANGELOG.md
internal/todos/todos.go
internal/todos/todos_test.go

Fixes an issue where the `TODOScanner.Scan` would return `false` if it encounters a multi-line comment with no TODOs present in it.
Fixes #1520
**Checklist:**

fix: TODO comments after multi-line comments.

---

internal/walker/walker.go
internal/walker/walker_test.go

Fix the line check for git blame results.
N/A
**Checklist:**

fix: git blame line check

---

internal/testutils/gitrepo.go
internal/testutils/gitrepo_test.go
internal/walker/walker.go
internal/walker/walker_test.go

Fix the relative path passed to `git.Blame` to be relative to the git repository root.
Fixes #1518 
**Checklist:**

fix: Fix relative paths to git repo for git blame paths

---

internal/cmd/todos/app.go

Mark the `--blame` flag feature as BETA for performance reasons.
N/A
**Checklist:**

chore: Mark blame feature as beta

---

CHANGELOG.md

Release v0.9.0
N/A
**Checklist:**

chore(release): v0.9.0

---

.gitignore
README.md

Update instrutions in `README.md`.
#1561 
**Checklist:**

fix: Installation instructions in `README.md` are failing due to `slsa-verifier` version being old

---

CHANGELOG.md
internal/cmd/todos/app.go
internal/cmd/todos/app_test.go
internal/walker/walker.go
internal/walker/walker_test.go

A new `--label` flag is added that takes a GLOB and matches against TODO labels. The flag can be included multilpe times. A TODO that matches any label is included in the output.
Fixes #1562
**Checklist:**

feat: --label GLOB filter

---

.github/workflows/pre-submit.units.yml
Makefile
go.mod
go.sum
internal/cmd/todos/app_test.go
internal/testutils/gitrepo_test.go
internal/testutils/tempdir_test.go
internal/todos/todos_test.go
internal/utils/slice_test.go
internal/vendoring/vendoring_test.go

- Bump sigs.k8s.io/release-utils from 0.8.4 to 0.8.5
- Update golangci-lint to 1.61.0 to fix a memory leak issue.
- Use the default `colored-line-number` output format for golangci-lint because `github-actions` is now deprecated.
- Fix golangci-lint errors
N/A
**Checklist:**

chore(deps): Bump sigs.k8s.io/release-utils from 0.8.4 to 0.8.5

---

internal/scanner/languages.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Add support for OCaml nested comments.
Fixes #1628 
**Checklist:**

feat: Add support for OCaml nested comments

---

README.md

- Fix old link to `todo-issue-reopener`
- Add a use case for generating documentation of TODOs
N/A
**Checklist:**

docs: Fix link and add use case

---

CHANGELOG.md
internal/scanner/comment.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go
internal/scanner/state.go
internal/todos/todos.go
internal/todos/todos_test.go

Fixed a bug where simple TODO block comments (e.g. `/* TODO */`) were not shown.
Fixes #1631
**Checklist:**

fix: simple TODO block comment

---

Makefile

Add `-mod=vendor` option to the `build` and `build-profile` make targets.
N/A
**Checklist:**

chore: use -mod=vendor

---

CHANGELOG.md
internal/cmd/todos/app.go
internal/cmd/todos/app_test.go
internal/cmd/todos/errors.go
internal/cmd/todos/main.go

BREAKING CHANGE: Set a non-zero exit code when TODOs are found to make `todos` act more like other linters and make it more scriptable.
Fixes #1657
Fixes #1620
**Checklist:**

feat!: Set non-zero exit code

---

.golangci.yml
cmd/todos/errors.go

Enable the `errname` linter.
Updates #1678
**Checklist:**

chore: enable errname linter

---

.golangci.yml
cmd/todos/app.go
internal/scanner/languages.go
internal/scanner/scanner_test.go
internal/todos/todos.go
internal/vendoring/vendoring.go
internal/walker/walker_test.go

Enable the `gochecknoglobals` linter.
n/a
**Checklist:**

chore: enable gochecknoglobals

---

cmd/todos/app.go
internal/todos/todos.go

Use `strings.SplitSeq` because it's slightly more efficient.
n/a
**Checklist:**

chore: Use strings.SplitSeq

---

.golangci.yml

Don't use `ireturn` since it's not very helpful and seems buggy.
Updates #1678
**Checklist:**

chore: Don't use ireturn

---

.golangci.yml

Don't use `maintidx` since it doesn't provide much value in addition to `gocyclo`, `cyclop`, and `gocognit`.
Updates #1678
**Checklist:**

chore: Don't use maintidx

---

.golangci.yml
internal/testutils/gitrepo.go
internal/testutils/tempdir.go

Enable the `mnd` linter.
Updates #1678
**Checklist:**

chore: Enable mnd

---

.golangci.yml
internal/scanner/scanner.go
internal/scanner/scanner_test.go
internal/scanner/state.go

Improve handling when line comment or multi-line comment start sequences overlap with string start sequences.
Fixes #1615 
Fixes #1616 
Fixes #1617 
**Checklist:**

chore: Improve handling of overlapping comments

---

.golangci.yml
cmd/todos/app.go
internal/scanner/scanner_test.go

Enable the `perfsprint` linter.
Updates #1678
**Checklist:**

chore: Enable perfsprint linter

---

.golangci.yml
internal/cmd/genlangdocs/main.go
internal/todos/todos.go

Enable the `prealloc` linter.
Updates #1678 
**Checklist:**

chore: enable prealloc linter

---

internal/walker/walker.go
internal/walker/walker_test.go

BREAKING CHANGE: Print an error for unsupported or binary files if they are explictly specified on the command line. This also causes `todos` to return a non-zero exit code. These files are ignored when walking a directory.
Fixes #1668 
**Checklist:**

feat!: print an error for unsupported files

---

.golangci.yml
internal/scanner/scanner_test.go

Enable the `usetesting` linter.
Updates #1678
**Checklist:**

chore: enable usetesting linter
